table fact_security_snapshot
	lineageTag: e2d7b858-6cfb-4988-a3d2-e8d10118cb92
	sourceLineageTag: [gold].[fact_security_snapshot]

	column ticker
		dataType: string
		lineageTag: 1db592d4-b73f-4e3a-8e0c-7a50efed5524
		sourceLineageTag: ticker
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column trading_days
		dataType: int64
		formatString: 0
		lineageTag: c293ab48-7582-4dbe-a3b5-5ad15d86339f
		sourceLineageTag: trading_days
		summarizeBy: none
		sourceColumn: trading_days

		annotation SummarizationSetBy = Automatic

	column date_from
		dataType: dateTime
		formatString: General Date
		lineageTag: f69af90f-c082-48cd-bfc0-9d01a6fbce33
		sourceLineageTag: date_from
		summarizeBy: none
		sourceColumn: date_from

		annotation SummarizationSetBy = Automatic

	column date_to
		dataType: dateTime
		formatString: General Date
		lineageTag: a1a59e0b-a0b7-4def-8b74-8fb5c79578f8
		sourceLineageTag: date_to
		summarizeBy: none
		sourceColumn: date_to

		annotation SummarizationSetBy = Automatic

	column annualised_return
		dataType: double
		lineageTag: 93f65918-9891-4878-b9d7-9d0ec3e24906
		sourceLineageTag: annualised_return
		summarizeBy: none
		sourceColumn: annualised_return

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annualised_volatility
		dataType: double
		lineageTag: 7d58ff1f-1f2d-4d40-bd52-9d2bb84462e4
		sourceLineageTag: annualised_volatility
		summarizeBy: none
		sourceColumn: annualised_volatility

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sharpe_ratio
		dataType: double
		lineageTag: 8c49affc-63f8-4cc3-96be-aabc1bb752b7
		sourceLineageTag: sharpe_ratio
		summarizeBy: none
		sourceColumn: sharpe_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_drawdown
		dataType: double
		lineageTag: 5f7145b8-a886-49f1-84fe-0971f3ff327c
		sourceLineageTag: max_drawdown
		summarizeBy: none
		sourceColumn: max_drawdown

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column market_cap
		dataType: int64
		formatString: 0
		lineageTag: f4a2719a-b594-4ad5-83bb-c643330cf453
		sourceLineageTag: market_cap
		summarizeBy: none
		sourceColumn: market_cap

		annotation SummarizationSetBy = Automatic

	column beta
		dataType: double
		lineageTag: deecc8c8-086e-4dec-8b1c-e62b5e5f173d
		sourceLineageTag: beta
		summarizeBy: none
		sourceColumn: beta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pe_ratio_ttm
		dataType: double
		lineageTag: a7c8c5f2-14cc-44e9-9cef-a3b988941996
		sourceLineageTag: pe_ratio_ttm
		summarizeBy: none
		sourceColumn: pe_ratio_ttm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pe_ratio_forward
		dataType: double
		lineageTag: b79edcac-1081-42e8-846f-a784ae1315c3
		sourceLineageTag: pe_ratio_forward
		summarizeBy: none
		sourceColumn: pe_ratio_forward

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price_to_book
		dataType: double
		lineageTag: 5dba3008-3ac4-45c7-a69e-f7e3a0ef2ed7
		sourceLineageTag: price_to_book
		summarizeBy: none
		sourceColumn: price_to_book

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dividend_yield
		dataType: double
		lineageTag: 529674cb-a3f1-4d43-a8b5-af415ae2d8ea
		sourceLineageTag: dividend_yield
		summarizeBy: none
		sourceColumn: dividend_yield

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column eps_ttm
		dataType: double
		lineageTag: 25a16839-d1c8-4f6a-8673-59867f2ed9ce
		sourceLineageTag: eps_ttm
		summarizeBy: none
		sourceColumn: eps_ttm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column return_on_equity
		dataType: double
		lineageTag: 2771b32a-4c77-4080-bbbf-f1b1a6c5765c
		sourceLineageTag: return_on_equity
		summarizeBy: none
		sourceColumn: return_on_equity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column return_on_assets
		dataType: double
		lineageTag: 4705965d-87a0-4a05-9855-344897acd7ba
		sourceLineageTag: return_on_assets
		summarizeBy: none
		sourceColumn: return_on_assets

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column operating_margin
		dataType: double
		lineageTag: 48f3dbdb-459d-492f-bee2-ddee06dec2fa
		sourceLineageTag: operating_margin
		summarizeBy: none
		sourceColumn: operating_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profit_margin
		dataType: double
		lineageTag: 3e48cdeb-2cbc-48b5-9f7a-7dd6c7a9927b
		sourceLineageTag: profit_margin
		summarizeBy: none
		sourceColumn: profit_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gross_margin
		dataType: double
		lineageTag: 233943af-7d5b-4c77-ae6e-d2c4c81c248d
		sourceLineageTag: gross_margin
		summarizeBy: none
		sourceColumn: gross_margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue_growth_yoy
		dataType: double
		lineageTag: 7336e89b-33e7-4e13-a545-43ce2a44d726
		sourceLineageTag: revenue_growth_yoy
		summarizeBy: none
		sourceColumn: revenue_growth_yoy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column earnings_growth_yoy
		dataType: double
		lineageTag: 3b825144-30a3-46b2-96af-e1153fca6533
		sourceLineageTag: earnings_growth_yoy
		summarizeBy: none
		sourceColumn: earnings_growth_yoy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debt_to_equity
		dataType: double
		lineageTag: 58214064-f25e-4ef9-b894-12e55be362aa
		sourceLineageTag: debt_to_equity
		summarizeBy: none
		sourceColumn: debt_to_equity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column current_ratio
		dataType: double
		lineageTag: 781cbd51-82e9-43eb-9c56-370eeb1c7460
		sourceLineageTag: current_ratio
		summarizeBy: none
		sourceColumn: current_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column enterprise_value
		dataType: double
		lineageTag: c529f9ef-9360-49de-991f-a2c6eabd3547
		sourceLineageTag: enterprise_value
		summarizeBy: none
		sourceColumn: enterprise_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ev_ebitda
		dataType: double
		lineageTag: 8bc62eae-f2b2-4f18-9877-97e7ec59ffe2
		sourceLineageTag: ev_ebitda
		summarizeBy: none
		sourceColumn: ev_ebitda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Securities' = COUNTROWS('dim_security')
		lineageTag: 5e068a2c-5e70-4728-84e7-2f6b9d2d65f3
		formatString: #,##0
		displayFolder: Overview

	measure 'Total Market Cap' = SUM('fact_security_snapshot'[market_cap])
		lineageTag: 25b55ab9-e56b-4e63-807e-de4f76435bf7
		formatString: #,##0
		displayFolder: Overview

	measure 'Avg Annualised Return' = AVERAGE('fact_security_snapshot'[annualised_return])
		lineageTag: 5030c8d5-dc3b-41cb-828e-e612ed844aec
		formatString: 0.00%
		displayFolder: Risk

	measure 'Avg Volatility' = AVERAGE('fact_security_snapshot'[annualised_volatility])
		lineageTag: f2d76be2-b42c-4950-9b70-a93c981cb9e8
		formatString: 0.00%
		displayFolder: Risk

	measure 'Avg Sharpe Ratio' = AVERAGEX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[sharpe_ratio])), 'fact_security_snapshot'[sharpe_ratio])
		lineageTag: 928b0ac9-5771-4581-a4ae-ce61d9678a91
		formatString: 0.00
		displayFolder: Risk

	measure 'Avg Max Drawdown' = AVERAGE('fact_security_snapshot'[max_drawdown])
		lineageTag: dbafce9d-8a1f-457e-81bf-d60f938ae9f6
		formatString: 0.00%
		displayFolder: Risk

	measure 'Best Sharpe Ratio' = MAXX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[sharpe_ratio])), 'fact_security_snapshot'[sharpe_ratio])
		lineageTag: d1ab66a2-e24d-403b-b645-1744ea7044d1
		formatString: 0.00
		displayFolder: Risk

	measure 'Worst Max Drawdown' = MINX('fact_security_snapshot', 'fact_security_snapshot'[max_drawdown])
		lineageTag: 892fcea2-6554-40f5-8d1b-f0dca49788f3
		formatString: 0.00%
		displayFolder: Risk

	measure 'Avg Beta' = AVERAGEX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[beta])), 'fact_security_snapshot'[beta])
		lineageTag: 62eb9d71-8c2b-4aaf-ab60-4a3fef68508d
		formatString: 0.00
		displayFolder: Risk

	measure 'Median P/E (TTM)' = MEDIAN('fact_security_snapshot'[pe_ratio_ttm])
		lineageTag: f07f19fc-8ace-4375-8280-caa50019eee1
		formatString: 0.0
		displayFolder: Valuation

	measure 'Median EV/EBITDA' = MEDIAN('fact_security_snapshot'[ev_ebitda])
		lineageTag: 78313583-d9d2-4e49-a486-6d8721435d37
		formatString: 0.0
		displayFolder: Valuation

	measure 'Avg Dividend Yield' = AVERAGEX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[dividend_yield])), 'fact_security_snapshot'[dividend_yield])
		lineageTag: ba8b55ec-e310-4513-816c-1d39ffb9202d
		formatString: 0.00%
		displayFolder: Valuation

	measure 'Avg Price-to-Book' = AVERAGEX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[price_to_book])), 'fact_security_snapshot'[price_to_book])
		lineageTag: 50aa25ec-aa82-469a-aab7-4ac0297fe359
		formatString: 0.00
		displayFolder: Valuation

	measure 'Avg Return on Equity' = AVERAGEX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[return_on_equity])), 'fact_security_snapshot'[return_on_equity])
		lineageTag: 1dcd7549-4867-45b7-901f-87c973d97029
		formatString: 0.00%
		displayFolder: Profitability

	measure 'Avg Operating Margin' = AVERAGEX(FILTER('fact_security_snapshot', NOT ISBLANK('fact_security_snapshot'[operating_margin])), 'fact_security_snapshot'[operating_margin])
		lineageTag: 30a6e71e-aaa3-4919-9e67-c4fc292c38ff
		formatString: 0.00%
		displayFolder: Profitability

	partition fact_security_snapshot = entity
		mode: directLake
		source
			entityName: fact_security_snapshot
			schemaName: gold
			expressionSource: 'DirectLake - LH_Bronze'

