{
  "model": {
    "culture": "en-US",
    "compatibilityLevel": 1605,
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "ValuationFactors",
        "description": "Snapshot valuation multiples, financial ratios, and latest annual financials. One row per security. Source: gold.gold__valuation_factors.",
        "columns": [
          { "name": "ticker",               "dataType": "string",   "sourceColumn": "ticker",               "isKey": true },
          { "name": "company_name",          "dataType": "string",   "sourceColumn": "company_name" },
          { "name": "sector",               "dataType": "string",   "sourceColumn": "sector" },
          { "name": "industry",             "dataType": "string",   "sourceColumn": "industry" },
          { "name": "country",              "dataType": "string",   "sourceColumn": "country" },
          { "name": "currency",             "dataType": "string",   "sourceColumn": "currency" },
          { "name": "market_cap",           "dataType": "int64",    "sourceColumn": "market_cap",           "formatString": "#,##0",  "displayFolder": "Market" },
          { "name": "beta",                 "dataType": "double",   "sourceColumn": "beta",                 "formatString": "0.00",   "displayFolder": "Market" },
          { "name": "pe_ratio_ttm",         "dataType": "double",   "sourceColumn": "pe_ratio_ttm",         "formatString": "0.0",    "displayFolder": "Valuation Multiples" },
          { "name": "pe_ratio_forward",     "dataType": "double",   "sourceColumn": "pe_ratio_forward",     "formatString": "0.0",    "displayFolder": "Valuation Multiples" },
          { "name": "price_to_book",        "dataType": "double",   "sourceColumn": "price_to_book",        "formatString": "0.00",   "displayFolder": "Valuation Multiples" },
          { "name": "dividend_yield",       "dataType": "double",   "sourceColumn": "dividend_yield",       "formatString": "0.00%",  "displayFolder": "Valuation Multiples" },
          { "name": "eps_ttm",              "dataType": "double",   "sourceColumn": "eps_ttm",              "formatString": "0.00",   "displayFolder": "Valuation Multiples" },
          { "name": "ev_ebitda",            "dataType": "double",   "sourceColumn": "ev_ebitda",            "formatString": "0.0",    "displayFolder": "Valuation Multiples" },
          { "name": "return_on_equity",     "dataType": "double",   "sourceColumn": "return_on_equity",     "formatString": "0.00%",  "displayFolder": "Profitability" },
          { "name": "return_on_assets",     "dataType": "double",   "sourceColumn": "return_on_assets",     "formatString": "0.00%",  "displayFolder": "Profitability" },
          { "name": "operating_margin",     "dataType": "double",   "sourceColumn": "operating_margin",     "formatString": "0.00%",  "displayFolder": "Profitability" },
          { "name": "profit_margin",        "dataType": "double",   "sourceColumn": "profit_margin",        "formatString": "0.00%",  "displayFolder": "Profitability" },
          { "name": "gross_margin",         "dataType": "double",   "sourceColumn": "gross_margin",         "formatString": "0.00%",  "displayFolder": "Profitability" },
          { "name": "revenue_growth_yoy",   "dataType": "double",   "sourceColumn": "revenue_growth_yoy",   "formatString": "0.00%",  "displayFolder": "Growth" },
          { "name": "earnings_growth_yoy",  "dataType": "double",   "sourceColumn": "earnings_growth_yoy",  "formatString": "0.00%",  "displayFolder": "Growth" },
          { "name": "debt_to_equity",       "dataType": "double",   "sourceColumn": "debt_to_equity",       "formatString": "0.00",   "displayFolder": "Leverage" },
          { "name": "current_ratio",        "dataType": "double",   "sourceColumn": "current_ratio",        "formatString": "0.00",   "displayFolder": "Leverage" },
          { "name": "latest_fiscal_year",   "dataType": "int64",    "sourceColumn": "latest_fiscal_year",   "formatString": "0",      "displayFolder": "Latest Financials" },
          { "name": "latest_period_end",    "dataType": "dateTime", "sourceColumn": "latest_period_end",    "formatString": "yyyy-MM-dd", "displayFolder": "Latest Financials" },
          { "name": "revenue",              "dataType": "double",   "sourceColumn": "revenue",              "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "gross_profit",         "dataType": "double",   "sourceColumn": "gross_profit",         "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "ebitda",               "dataType": "double",   "sourceColumn": "ebitda",               "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "net_income",           "dataType": "double",   "sourceColumn": "net_income",           "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "eps_diluted",          "dataType": "double",   "sourceColumn": "eps_diluted",          "formatString": "0.00",   "displayFolder": "Latest Financials" },
          { "name": "total_assets",         "dataType": "double",   "sourceColumn": "total_assets",         "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "book_equity",          "dataType": "double",   "sourceColumn": "book_equity",          "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "total_debt",           "dataType": "double",   "sourceColumn": "total_debt",           "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "cash",                 "dataType": "double",   "sourceColumn": "cash",                 "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "net_debt",             "dataType": "double",   "sourceColumn": "net_debt",             "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "free_cash_flow",       "dataType": "double",   "sourceColumn": "free_cash_flow",       "formatString": "#,##0",  "displayFolder": "Latest Financials" },
          { "name": "enterprise_value",     "dataType": "double",   "sourceColumn": "enterprise_value",     "formatString": "#,##0",  "displayFolder": "Latest Financials" }
        ],
        "partitions": [
          {
            "name": "DirectLake",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "expressionSource": "LH_Bronze",
              "entityName": "gold__valuation_factors",
              "schemaName": "gold"
            }
          }
        ]
      },
      {
        "name": "RiskMetrics",
        "description": "Annualised return, volatility, Sharpe ratio, and max drawdown per ticker. One row per security. Source: gold.gold__risk_metrics.",
        "columns": [
          { "name": "ticker",                "dataType": "string",   "sourceColumn": "ticker",                "isHidden": true },
          { "name": "trading_days",          "dataType": "int64",    "sourceColumn": "trading_days",          "formatString": "#,##0" },
          { "name": "date_from",             "dataType": "dateTime", "sourceColumn": "date_from",             "formatString": "yyyy-MM-dd" },
          { "name": "date_to",               "dataType": "dateTime", "sourceColumn": "date_to",               "formatString": "yyyy-MM-dd" },
          { "name": "annualised_return",     "dataType": "double",   "sourceColumn": "annualised_return",     "formatString": "0.00%" },
          { "name": "annualised_volatility", "dataType": "double",   "sourceColumn": "annualised_volatility", "formatString": "0.00%" },
          { "name": "sharpe_ratio",          "dataType": "double",   "sourceColumn": "sharpe_ratio",          "formatString": "0.00" },
          { "name": "max_drawdown",          "dataType": "double",   "sourceColumn": "max_drawdown",          "formatString": "0.00%" },
          { "name": "beta",                  "dataType": "double",   "sourceColumn": "beta",                  "formatString": "0.00" },
          { "name": "sector",                "dataType": "string",   "sourceColumn": "sector",                "isHidden": true },
          { "name": "market_cap",            "dataType": "int64",    "sourceColumn": "market_cap",            "isHidden": true }
        ],
        "partitions": [
          {
            "name": "DirectLake",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "expressionSource": "LH_Bronze",
              "entityName": "gold__risk_metrics",
              "schemaName": "gold"
            }
          }
        ]
      },
      {
        "name": "ReturnCovariance",
        "description": "Pairwise log-return correlation and annualised covariance matrix. One row per (ticker_a, ticker_b) pair. Source: gold.gold__return_covariance.",
        "columns": [
          { "name": "ticker_a",            "dataType": "string", "sourceColumn": "ticker_a" },
          { "name": "ticker_b",            "dataType": "string", "sourceColumn": "ticker_b" },
          { "name": "correlation",         "dataType": "double", "sourceColumn": "correlation",         "formatString": "0.0000" },
          { "name": "covariance_daily",    "dataType": "double", "sourceColumn": "covariance_daily",    "formatString": "0.000000" },
          { "name": "covariance_annual",   "dataType": "double", "sourceColumn": "covariance_annual",   "formatString": "0.0000" },
          { "name": "common_trading_days", "dataType": "int64",  "sourceColumn": "common_trading_days", "formatString": "#,##0" },
          { "name": "sector_a",            "dataType": "string", "sourceColumn": "sector_a" },
          { "name": "sector_b",            "dataType": "string", "sourceColumn": "sector_b" }
        ],
        "partitions": [
          {
            "name": "DirectLake",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "expressionSource": "LH_Bronze",
              "entityName": "gold__return_covariance",
              "schemaName": "gold"
            }
          }
        ]
      },
      {
        "name": "Date",
        "description": "Date dimension for filtering by fiscal year end date.",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "isKey": true,
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Month No",
            "dataType": "int64",
            "sourceColumn": "Month No",
            "isHidden": true,
            "formatString": "0"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name",
            "sortByColumn": "Month No"
          },
          {
            "name": "Year-Quarter",
            "dataType": "string",
            "sourceColumn": "Year-Quarter"
          },
          {
            "name": "Year-Month",
            "dataType": "string",
            "sourceColumn": "Year-Month"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "ADDCOLUMNS(",
                "    CALENDAR( DATE(2000, 1, 1), DATE(2035, 12, 31) ),",
                "    \"Year\",         YEAR( [Date] ),",
                "    \"Quarter\",      \"Q\" & FORMAT( ROUNDUP( MONTH([Date]) / 3, 0 ), \"0\" ),",
                "    \"Month No\",     MONTH( [Date] ),",
                "    \"Month Name\",   FORMAT( [Date], \"MMM\" ),",
                "    \"Year-Quarter\", FORMAT( [Date], \"YYYY\" ) & \" Q\" & FORMAT( ROUNDUP( MONTH([Date]) / 3, 0 ), \"0\" ),",
                "    \"Year-Month\",   FORMAT( [Date], \"YYYY MMM\" )",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          { "name": "__PBI_TableCategory", "value": "Time" }
        ]
      },
      {
        "name": "_Measures",
        "description": "DAX measures for financial analysis.",
        "columns": [
          {
            "name": "column_placeholder",
            "dataType": "string",
            "sourceColumn": "column_placeholder",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DATATABLE(\"column_placeholder\", STRING, {{\"\"}})"
            }
          }
        ],
        "measures": [
          {
            "name": "# Securities",
            "expression": "COUNTROWS( 'ValuationFactors' )",
            "formatString": "#,##0",
            "displayFolder": "Overview"
          },
          {
            "name": "Total Market Cap",
            "expression": "SUM( 'ValuationFactors'[market_cap] )",
            "formatString": "#,##0",
            "displayFolder": "Overview",
            "description": "Sum of market capitalisation for all selected securities. Mix of USD and AUD — filter by currency before comparing."
          },
          {
            "name": "Avg Annualised Return",
            "expression": "AVERAGE( 'RiskMetrics'[annualised_return] )",
            "formatString": "0.00%",
            "displayFolder": "Risk"
          },
          {
            "name": "Avg Volatility",
            "expression": "AVERAGE( 'RiskMetrics'[annualised_volatility] )",
            "formatString": "0.00%",
            "displayFolder": "Risk"
          },
          {
            "name": "Avg Sharpe Ratio",
            "expression": "AVERAGEX(\n    FILTER( 'RiskMetrics', NOT ISBLANK( 'RiskMetrics'[sharpe_ratio] ) ),\n    'RiskMetrics'[sharpe_ratio]\n)",
            "formatString": "0.00",
            "displayFolder": "Risk"
          },
          {
            "name": "Avg Max Drawdown",
            "expression": "AVERAGE( 'RiskMetrics'[max_drawdown] )",
            "formatString": "0.00%",
            "displayFolder": "Risk",
            "description": "Average maximum peak-to-trough decline. Negative values; closer to 0 is better."
          },
          {
            "name": "Best Sharpe Ratio",
            "expression": "MAXX( FILTER( 'RiskMetrics', NOT ISBLANK( 'RiskMetrics'[sharpe_ratio] ) ), 'RiskMetrics'[sharpe_ratio] )",
            "formatString": "0.00",
            "displayFolder": "Risk"
          },
          {
            "name": "Worst Max Drawdown",
            "expression": "MINX( 'RiskMetrics', 'RiskMetrics'[max_drawdown] )",
            "formatString": "0.00%",
            "displayFolder": "Risk"
          },
          {
            "name": "Avg Beta",
            "expression": "AVERAGEX(\n    FILTER( 'ValuationFactors', NOT ISBLANK( 'ValuationFactors'[beta] ) ),\n    'ValuationFactors'[beta]\n)",
            "formatString": "0.00",
            "displayFolder": "Risk"
          },
          {
            "name": "Median P/E (TTM)",
            "expression": "MEDIAN( 'ValuationFactors'[pe_ratio_ttm] )",
            "formatString": "0.0",
            "displayFolder": "Valuation"
          },
          {
            "name": "Median EV/EBITDA",
            "expression": "MEDIAN( 'ValuationFactors'[ev_ebitda] )",
            "formatString": "0.0",
            "displayFolder": "Valuation"
          },
          {
            "name": "Avg Dividend Yield",
            "expression": "AVERAGEX(\n    FILTER( 'ValuationFactors', NOT ISBLANK( 'ValuationFactors'[dividend_yield] ) ),\n    'ValuationFactors'[dividend_yield]\n)",
            "formatString": "0.00%",
            "displayFolder": "Valuation"
          },
          {
            "name": "Avg Price-to-Book",
            "expression": "AVERAGEX(\n    FILTER( 'ValuationFactors', NOT ISBLANK( 'ValuationFactors'[price_to_book] ) ),\n    'ValuationFactors'[price_to_book]\n)",
            "formatString": "0.00",
            "displayFolder": "Valuation"
          },
          {
            "name": "Avg Return on Equity",
            "expression": "AVERAGEX(\n    FILTER( 'ValuationFactors', NOT ISBLANK( 'ValuationFactors'[return_on_equity] ) ),\n    'ValuationFactors'[return_on_equity]\n)",
            "formatString": "0.00%",
            "displayFolder": "Profitability"
          },
          {
            "name": "Avg Operating Margin",
            "expression": "AVERAGEX(\n    FILTER( 'ValuationFactors', NOT ISBLANK( 'ValuationFactors'[operating_margin] ) ),\n    'ValuationFactors'[operating_margin]\n)",
            "formatString": "0.00%",
            "displayFolder": "Profitability"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "RiskMetrics_to_ValuationFactors",
        "fromTable": "RiskMetrics",
        "fromColumn": "ticker",
        "toTable": "ValuationFactors",
        "toColumn": "ticker",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "ReturnCovariance_TickerA_to_ValuationFactors",
        "fromTable": "ReturnCovariance",
        "fromColumn": "ticker_a",
        "toTable": "ValuationFactors",
        "toColumn": "ticker",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "ReturnCovariance_TickerB_to_ValuationFactors",
        "fromTable": "ReturnCovariance",
        "fromColumn": "ticker_b",
        "toTable": "ValuationFactors",
        "toColumn": "ticker",
        "crossFilteringBehavior": "oneDirection",
        "isActive": false
      },
      {
        "name": "ValuationFactors_to_Date",
        "fromTable": "ValuationFactors",
        "fromColumn": "latest_period_end",
        "toTable": "Date",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "LH_Bronze",
        "annotations": [
          { "name": "isDirectLakeSource", "value": "True" }
        ],
        "kind": "m",
        "expression": [
          "let",
          "    Source = Lakehouse.Contents(null)[Data]{[workspaceId=\"{WORKSPACE_ID}\",lakehouseId=\"{LAKEHOUSE_ID}\"]}[Data]",
          "in",
          "    Source"
        ]
      }
    ],
    "annotations": [
      { "name": "__PBI_TimeIntelligenceEnabled", "value": "1" }
    ]
  }
}
